name: Compile and Test Linux-x64

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Linux x64
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Get toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test

    - name: Build Debug Target
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Build Release Target
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
