
name: Cross-compile armv7

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - arm-unknown-linux-gnueabihf

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Get ARM toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build Debug Target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target=${{ matrix.target }}

      - name: Build Release Target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Optimize Release Target
        run: |
          ls -alh target/arm-unknown-linux-gnueabihf/release/gnss-mgr

      - name: Compress binaries
            uses: svenstaro/upx-action@v2
            with:
              file: target/arm-unknown-linux-gnueabihf/release/gnss-mgr

      - name: List
        run: |
          ls -alh target/arm-unknown-linux-gnueabihf/release/gnss-mgr
