
name: Cross-compile armv7

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - arm-unknown-linux-gnueabihf

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Get ARM toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: ARM binutil (strip)
        uses: numworks/setup-arm-toolchain@v1
      - name: test gcc
        run: arm-none-eabi-gcc --version
        continue-on-error: true
      - name: test strip
        run: arm-none-eabi-strip
        continue-on-error: true

      - name: toolchains
        run: rustup target list

      #- name: Build Debug Target
      #  uses: actions-rs/cargo@v1
      #  with:
      #    use-cross: true
      #    command: build
      #    args: --target=${{ matrix.target }}

      - name: Build Release Target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Optimize Release Target
        run: |
          ls -alh target/arm-unknown-linux-gnueabihf/release/gnss-mgr
          arm-none-eabi-strip target/arm-unknown-linux-gnueabihf/release/gnss-mgr

      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: gnss-mgr
          path: target/arm-unknown-linux-gnueabihf/release/gnss-mgr
